### ISSUE TITLE
Earthwarm Jim 1-2 joystick issues

### ISSUE THREAD

**Issue by cruz1383** [0mhz-net/0mhz-collection#15]
I tried to run it with an 8bitdo sn30 controller but I can't get it to register the controller. In the game's built-in Options menu, there is a setting for configuring a joystick, but when I try to configure it, none of the directions work (only the button for whip works). If I go into game without configuring, the joypad does not work for me. I tried to esc out of the game and into DOS and typing dir in DOS and then setup but that only let me setup the sound card and not the joystick controller.

**Comment by emubastard** [comment]
I have tested this and have the same issue with an Xbox controller.  Joystick support is hit and miss in the collection due to compatibility.  None of the options in the core fixed it.  ao486 core is amazing but DOS is also wildly non standard in how things are implemented.  This game will have to be played with keyboard unless someone else can figure something out.

My apologies.
