### ISSUE TITLE
Update ao486.cfg

### ISSUE THREAD

**Issue by limi** [0mhz-net/0mhz-collection#2]
The scaling should probably be `Native` instead of `4x` (it has worked great on every game I have tried so far, but may be a setting that forces 15kHz? Must investigate with more games), and we should probably also include a standard set of scanline/shadow mask presets, like AmigaVision does. Makes those DOS games look so much better.

**Comment by emubastard** [comment]
Native sets 1khz, and VGA scanned at 31khz.  So 4X actually looks how VGA is suppose to look.

It's really up to personal preference though.  I thought all the configures were set to 4X as that is how it appears more like what the CRT output should show.  We're also going to double check this on a CRT.

**Comment by M-Walrus** [comment]
Scaling should probably be left with standard interpolation (gaussian sharp 85-90 would be a good baseline) since the video output modes can vary wildly across the DOS library.  Since the filter quality was improved on MiSTer a few years back and the entire structure had to be re-created, some things that were available before never made it to the new filters, including the VGA double-scan filter (called "High Res scanlines" before IIRC).  We need someone to re-create this filter, and update the entire adaptive set of scanlines in general to the new capabilities of the scaler/filter system, but this still has not happened as of this post.  Given this is the case currently I would suggest just sticking with standard interpolation and letting users customize further to their liking on a game-by-game basis.

**Comment by emubastard** [comment]
Switching LOW-RES back to native.  It will be in the next upload.
