### ISSUE TITLE
How can one contribute to this project?

### ISSUE THREAD

**Issue by Firehawke** [0mhz-net/0mhz-collection#73]
I've got at least two working game setups (Silpheed and One Must Fall 2097) that I'll adapt to your format if you've got documentation on what I need to do to get it all in a form you can use.

**Comment by thisisacleverusername** [comment]
As I understand, [emubastard](https://github.com/emubastard) is choosy about not bloating the collection. That said, I don't really know why - users can pick and choose, that's kind of the whole point. 

Either way, you don't really need him to add a game to his official list to be accessible  -- you can upload to archive on your own account and add the subject tag "0MHz DOS Collection"  It'll appear in the official search when a user visits https://0mhz.net/download

As it turns out, Silpheed is already uploaded. 

There's also an "unofficial collection" uploaded by MiSTerTea: https://archive.org/details/@etalos/lists/1/0mhz-dos-collection-addons . There's a setting in the 0mhz downloader script to also include this collection. Perhaps it would be easier to offer your work to MiSTerTea for inclusion?

**Comment by Firehawke** [comment]
I'm pretty sure the Silpheed revision I have isn't going to be in any existing collection. It's a hybrid of the IBM PS/1 and the previous PC release, giving the original game the upgrades the PS/1-only version got while retaining the hardware support for Sound Blaster, etc.
