### ISSUE TITLE
CHD format

### ISSUE THREAD

**Issue by Scandal-UK** [0mhz-net/0mhz-collection#9]
Just wondering if the ISO/BIN images can be compressed to CHD format? Is there a reason not to use CHD?

I had a look at the first game in the list (7th Guest) but the .mgl file has a typo in the directory for the ISO (it's pointing at folder "7thguestc"). I thought the first game would be 4D Sports Driving but that game is called Stunts once extracted(!)

Hopefully that's not indicative of the remaining titles but it was just the first two that I have checked.

**Comment by M-Walrus** [comment]
CHD should be preferable as it would save a lot of space, especially given the overall bloat of many of the vhd images from the way this is structured (16MB for a 3mb game in Super Cars International, for instance.)  Saving as much room in order to offset this would be a good reason to use CHD.  With the many CD consoles/computers now on MiSTer, SD card space is at a premium for many folks.

4D Sports driving is a later euro release of Stunts by Mindscape, and is one of the worse versions of the game.  I generally try to compare different versions of games like this (when there are significant differences) when making videos for them and found the v1.1 Broderbund release of Stunts to be the best.  The comparison is in the description here if you'd like to know the reasoning: https://youtu.be/GRop6sOiQ4o

**Comment by emubastard** [comment]
I've completed work on converting ISO and CUE files to CHD.  The collection went should be 6GB smaller when fully uncompressed from zips.  Uploads will be updated soon.

**Comment by Scandal-UK** [comment]
Excellent work
